version: '3.1'

services:

  wordpress:
    image: wordpress:5.7
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: th221146_thfb
      WORDPRESS_DB_PASSWORD: 8U6iTb@s9#
      WORDPRESS_DB_NAME: th221146_thfb
      WORDPRESS_TABLE_PREFIX: thfb32_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'ALLOW_UNFILTERED_UPLOADS', true );
    volumes:
    - wordpress:/var/www/html
    - ./theme:/var/www/html/wp-content/themes/thfb/
    - ./plugins:/var/www/html/wp-content/plugins/
    - ./uploads:/var/www/html/wp-content/uploads/
    - ./languages:/var/www/html/wp-content/languages/

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: th221146_thfb
      MYSQL_USER: th221146_thfb
      MYSQL_PASSWORD: 8U6iTb@s9#
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
    - PMA_USER=th221146_thfb
    - PMA_PASSWORD=8U6iTb@s9#
    ports:
    - 8888:80
    volumes:
    - /sessions
volumes:
  wordpress: